# Generated by Django 5.1.1 on 2025-10-26 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programas_Cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='slug',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default='curso-default', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='icono',
            field=models.CharField(default='📚', max_length=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
        migrations.AddField(
            model_name='curso',
            name='subtitulo',
            field=models.CharField(default='Subtítulo del Curso', max_length=300),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(default='Título del Curso', max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default='Descripción del curso'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('progreso', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='Programas_Cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
